language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_install:
  - composer self-update

install:
  - composer install --dev --no-interaction --prefer-source

script:
  - vendor/bin/phpunit -c tests/phpunit.xml.dist
